Tutorial

In [1]:
# load in libraries
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
# practice data of flowers, 2 species and 50 samples each
iris = datasets.load_iris()
X = iris.data[:, :2]
y = iris.target

# split into training and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# sets 30% for test and 70% for training

model = SVC(kernel='rbf') #from SVM scikit-learn library, uses radial basis function

# train the data using fit
model.fit(X_train, y_train)

# make predictions based on the testing data from before
y_pred = model.predict(X_test)

# evauluate the performance of the SVM model by caclulating confusino matrix
# and the accuracy score
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix: \n", cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

Confusion Matrix: 
 [[16  0  0]
 [ 0 13  5]
 [ 0  4  7]]
Accuracy:  0.8


Create dummy data

In [9]:
# load in libraries
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [ ]:
### Creating dummy data ###
# Parameters
fs = 255             # Sampling frequency in Hz
n_points = fs        # 1 second of data
n_samples_per_class = 100

# Time vector (not used for SVM but useful for plotting)
t = np.linspace(0, 1, n_points, endpoint=False)

def generate_eeg(class_label, n_samples):
    data = []
    labels = []
    for _ in range(n_samples):
        # Start with baseline noise
        eeg = np.random.normal(0, 1, n_points)
        if class_label == 'learned':
            # Simulate a negative deflection (N400-like) around 400 ms (samples 100 to 110)
            eeg[100:110] += -5  
        data.append(eeg)
        labels.append(class_label)
    return np.array(data), np.array(labels)

# Generate dummy EEG data for both classes
X_learned, y_learned = generate_eeg('learned', n_samples_per_class)
X_not_learned, y_not_learned = generate_eeg('not_learned', n_samples_per_class)


In [16]:
# combine and shuffle data to avoid svm learning from temporal patterns
X = np.concatenate((X_learned, X_not_learned), axis=0)
y = np.concatenate((y_learned, y_not_learned), axis=0)
indices = np.random.permutation(len(y))
X, y = X[indices], y[indices]

# split into training and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# kernel trick
model = SVC(kernel='rbf') #from SVM scikit-learn library, uses radial basis function

# train model
model.fit(X_train, y_train)

# make predictions
y_pred = model.predict(X_test)

# evauluate the performance of the SVM model by caclulating confusino matrix
# and the accuracy score
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix: \n", cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

Confusion Matrix: 
 [[31  0]
 [ 0 29]]
Accuracy:  1.0


Try with real data